export {
  breakpoints,
  isVPXs,
  isVPSm,
  isVPMinSm,
  isVPMaxSm,
  isVPMd,
  isVPMinMd,
  isVPMaxMd,
  isVPLg,
  isVPMinLg,
  isVPMaxLg,
  isVPXl,
  isVPLandscape,
  isVPXsAndLandscape,
  isVPMaxSmAndLandscape,
  isVPXsAndPortrait,
  isVPSmAndPortrait,
  isHoverable,
  prefersDarkMode,
} from './config'
